import turtle
turtle.bgcolor("lightblue")
zoo=turtle.Turtle()
chucha=turtle.Turtle()
textovik=turtle.Turtle()
chucha.speed(200)
zoo.speed(200)
chucha.up()
chucha.goto(0,-50)
chucha.down()
turtle.speed(200)
chucha.pensize(5)
chucha.fillcolor("grey")
chucha.begin_fill()
chucha.up()
chucha.backward(50)
chucha.left(90)
chucha.forward(50)
chucha.right(90)

chucha.down()
chucha.left(55)
chucha.pencolor("dim grey")
for i in range(4):
    chucha.left(45)
    chucha.forward(100)
    chucha.right(45)
    chucha.forward(100)
    chucha.right(45)
    chucha.forward(100)
chucha.right(67.5)
chucha.forward(630)
chucha.end_fill()
turtle.bgcolor("lightblue")
turtle.pencolor("green")
turtle.fillcolor("lightgreen")
turtle.begin_fill()
turtle.forward(2000)
turtle.right(90)
turtle.forward(700)
turtle.right(90)
turtle.forward(4000)
turtle.right(90)
turtle.forward(700)
turtle.right(90)
turtle.forward(2000)
turtle.end_fill()
zoo.hideturtle()
zoo.lt(90)
#recursion
def draw(l):
    if(l<10):
        return
    else:
        zoo.forward(l)
        zoo.left(30)
        draw(l/2)
        zoo.right(60)
        draw(l/2)
        zoo.left(30)
        zoo.backward(l)

zoo.pensize(5)
zoo.color("green","red")
zoo.up()
zoo.goto(-200,-350)
zoo.down()
draw(120)
zoo.goto(-50,-200)
draw(100)
zoo.goto(50,-100)
draw(80)
zoo.goto(100,-50)
zoo.up()
zoo.goto(50,-350)
zoo.down()
zoo.goto(250,-50)
textovik.up()
textovik.goto(100,300)
textovik.backward(700)
textovik.down()
textovik.pensize(3)
textovik.up()
textovik.write("Вы находитесь в землях, заселенных драконами.", font=("Arial", 16, "normal"))
textovik.right(90)
textovik.forward(20)
textovik.left(90)
textovik.write("Перед собой вы видите две пещеры.", font=("Arial", 16, "normal"))
textovik.right(90)
textovik.forward(20)
textovik.left(90)
textovik.write("В одной из них — дружелюбный дракон,", font=("Arial", 16, "normal"))
textovik.right(90)
textovik.forward(20)
textovik.left(90)
textovik.write("который готов поделиться с вами своими сокровищами.", font=("Arial", 16, "normal"))
textovik.right(90)
textovik.forward(20)
textovik.left(90)
textovik.write("Во второй — `жадный и голодный дракон, который мигом вас съест.", font=("Arial", 16, "normal"))
chucha.up()
chucha.goto(60,250)
chucha.right(245)
chucha.forward(150)
chucha.down()
chucha.pencolor("darkgrey")
chucha.fillcolor("dim grey")
chucha.begin_fill()
chucha.circle(80)
chucha.circle(70)
chucha.end_fill()
chucha.up()
chucha.goto(300,80)
chucha.down()
chucha.pencolor("darkgrey")
chucha.fillcolor("dim grey")
chucha.begin_fill()
chucha.circle(80)
chucha.circle(70)
chucha.up()
chucha.end_fill()
