import turtle
turtle.speed(200)
turtle.width(2)
turtle.up()
turtle.backward(500)
turtle.right(7)
turtle.down()
for i in range(6):
    turtle.circle(45,90)
    turtle.circle(-45,90)
    turtle.circle(-30,90)
    turtle.circle(-15,90)
    turtle.circle(-15,90)
    turtle.circle(10,90)
    turtle.circle(10,90)
    turtle.circle(45,90)
turtle.up()
turtle.right(96)
turtle.forward(200)
turtle.left(96)
turtle.backward(500)
turtle.left(7)
turtle.down()
#=====================================================================================================================================
for i in range(6):
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(80)
    turtle.right(90)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(35)
    turtle.left(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(65)
    turtle.left(90)
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(90)
    turtle.left(90)
    turtle.forward(105)
turtle.up()
turtle.left(90)
turtle.forward(350)
turtle.left(90)
turtle.forward(750)
turtle.right(180)
turtle.down()

#=====================================================================================================================================
for i in range(4):
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(120)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(35)
    turtle.left(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(50)
turtle.up()
turtle.right(90)
turtle.forward(500)
turtle.left(90)
turtle.backward(700)
turtle.down()
#=====================================================================================================================================
for i in range(5):
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(40)
    
    
    
   




